/// <reference types="vitest" />
import { defineConfig, type Plugin } from 'vite';
import react from '@vitejs/plugin-react';
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

const walk = (dir: string): string[] => readdirSync(dir).flatMap((f) => (statSync(join(dir, f)).isDirectory() ? walk(join(dir, f)) : [join(dir, f)]));

/** Writes dist/sw.js after the build: every built file is saved on first load, so the app opens offline (L-2).
 *  It only ever deletes its own caches (judya-*), never the old MedMate app's cache. */
function offlineWorker(): Plugin {
  return {
    name: 'judya-offline-worker', apply: 'build',
    closeBundle() {
      const dist = join(process.cwd(), 'dist');
      const files = walk(dist).map((f) => relative(dist, f).split('\\').join('/')).filter((f) => f !== 'sw.js' && !f.endsWith('.map')).sort();
      const version = createHash('sha1').update(files.map((f) => f + readFileSync(join(dist, f)).length).join('|')).digest('hex').slice(0, 10);
      writeFileSync(join(dist, 'sw.js'), `// generated by vite.config.ts
const V = 'judya-${version}';
const FILES = ${JSON.stringify(['./', ...files])};
self.addEventListener('install', (e) => { e.waitUntil(caches.open(V).then((c) => c.addAll(FILES)).then(() => self.skipWaiting())); });
self.addEventListener('activate', (e) => { e.waitUntil(caches.keys().then((ks) => Promise.all(ks.filter((k) => k.startsWith('judya-') && k !== V).map((k) => caches.delete(k)))).then(() => self.clients.claim())); });
self.addEventListener('fetch', (e) => {
  const r = e.request;
  if (r.method !== 'GET' || new URL(r.url).origin !== self.location.origin) return;
  if (r.mode === 'navigate') { e.respondWith(fetch(r).catch(() => caches.match('./index.html', { ignoreVary: true }).then((m) => m || caches.match('./', { ignoreVary: true })))); return; }
  e.respondWith(caches.match(r, { ignoreVary: true }).then((m) => m || fetch(r)));
});
`);
    },
  };
}

// base './' so the build works under any Pages path (the site lives at /JudYa/, ADR-0006/0007)
export default defineConfig({
  base: './',
  plugins: [react(), offlineWorker()],
  build: { outDir: 'dist', sourcemap: false },
  test: { environment: 'jsdom', setupFiles: ['./src/test-setup.ts'], css: false },
});
